### ISSUE TITLE
Issue Title

### ISSUE THREAD

**Issue by GABXZV** [github/gemoji#300]
```[tasklist]
### Tasks
- [ ] https://github.com/github/gemoji/issues/298
```

```[tasklist]
### Tasks
- [ ] https://github.com/github/gemoji/issues/298
- [ ] https://github.com/github/gemoji/issues/205
- [x] [![Test](https://github.com/github/gemoji/actions/workflows/test.yml/badge.svg?branch=master)](https://github.com/github/gemoji/actions/workflows/test.yml
- [ ] https://github.com/github/gemoji/issues/289
- [ ] https://github.com/github/gemoji/pull/292
- [ ] [![Test](https://github.com/github/gemoji/actions/workflows/test.yml/badge.svg?branch=master)](https://github.com/github/gemoji/actions/workflows/test.yml)
- [ ] https://github.com/github/gemoji/pull/281
- [ ] https://github.com/github/gemoji/issues/293
- [ ] https://github.com/github/gemoji/issues/291
```
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```
